---
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_CPANEL_USER/public_html/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
